# Autogenerated wrapper script for Qt6Svg_jll for i686-w64-mingw32-cxx11
export libqt6svg, libqt6svgwidgets

using Qt6Base_jll
JLLWrappers.@generate_wrapper_header("Qt6Svg")
JLLWrappers.@declare_library_product(libqt6svg, "Qt6Svg.dll")
JLLWrappers.@declare_library_product(libqt6svgwidgets, "Qt6SvgWidgets.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll)
    JLLWrappers.@init_library_product(
        libqt6svg,
        "bin\\Qt6Svg.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6svgwidgets,
        "bin\\Qt6SvgWidgets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
